version: "3"
services:
  openhab:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - "/mnt/backup/pupici-prd/openhab/:/mnt/backup:rw"
    environment:
      - USER_ID=999
      - GROUP_ID=998
  theia:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - USER_ID=999
      - GROUP_ID=998
    user: 999:998
  nodered:
    environment:
      - USER_ID=999
      - GROUP_ID=998      
  influxdb:
    volumes:
      - "/mnt/backup/pupici-prd/influxdb/:/mnt/backup:rw"