defaultEntryPoints = ["http", "https"]

logLevel = "INFO" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]
        [[entryPoints.https.tls.certificates]]
        certFile = "/etc/traefik/assets/secure.pupici-prd.crt"
        keyFile = "/etc/traefik/assets/secure.pupici-prd.key.insecure"

[traefikLog]
  filePath = "/var/log/traefik/traefik.log.json"
  format   = "json"

[accessLog]
  filePath = "/var/log/traefik/access.log.json"
  format = "json"

# Connection to docker host system (docker.sock)
[docker]
watch = true
# This will hide all docker containers that don't have explicitly  
# set label to "enable"
exposedbydefault = false